import "./globals.css";

export const metadata = {
  title: "ToDo App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ fontFamily: '"Wittgenstein", serif' }}>{children}</body>
    </html>
  );
}
